bitwarden/directory-connector

src/services/gsuite-directory.service.ts

The current implementation for fetching groups is limited to the first 200 groups. This PR uses the pageToken from Google to fetch all groups.

Manage multiple pages when fetching G Suite groups

---

src/services/gsuite-directory.service.ts

The current implementation for fetching users is limited to the first 100 users. This PR uses the pageToken from Google to fetch all users.

Manage multiple pages when fetching G Suite users

---

src/app/accounts/login.component.html
src/app/accounts/sso.component.html
src/app/accounts/sso.component.ts
src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/services/services.module.ts
src/main.ts

Support SSO login from desktop app
- Stub out SSO component
- Process deep link callback
This solution is incomplete. Needs the following still:
- Localization strings
- Set password flow
I'd also like to consider kicking the org identifier collection process over to the web vault. This would avoid some routing issues that currently exist on processing the callback.

sso login from bwdc desktop app

---

src/services/gsuite-directory.service.ts

This should ask the gSuite API to enumerate all users in dynamic groups etc: https://developers.google.com/admin-sdk/directory/v1/reference/members/list#request

Fix for #55

---

src/app/accounts/login.component.html
src/app/accounts/login.component.ts
src/app/accounts/sso.component.html
src/app/accounts/sso.component.ts
src/locales/en/messages.json

- localize strings
- launch sso from login page

support launching sso from login page button

---

src/services/gsuite-directory.service.ts

Quick fix for lint errors (w/o muddying up what I'm currently working on with unrelated changes).

Fix lint errors/warnings

---

src/package.json

Version bump and jslib update to latest. Preparing for a patch release of bwdc. See: #41

Version bump + jslib update

---

src/app/services/services.module.ts
src/bwdc.ts
src/main.ts

> Update `jslib` to the latest
- **jslib**: update to 48144a7

[jslib] Update (48144a7)

---

src/package.json

version bump 2.9.0

---

.github/workflows/build.yml

Adding the build assets the the `rc` branch action runs
- .github/workflows/build.yml

adding the build assets for the rc branch

---

src/services/azure-directory.service.ts

Apparently Azure AD gets angry when you try to check user groups for a deleted user and responds with the error:
```
Resource <deleted user ID> does not exist or one of its queried reference-property objects are not present
```
This took a while to figure out, of course, because when you look in AD at the deleted user, they are indeed still in that group, and if you restore the user, they are in the group, but if they're currently "deleted" and you try to run `checkUserGroups` through the graph API, you get an error.
Previously this check was contained within a `try {} catch {}` block, however that was removed due to other downstream failures causing issues (for different reasons) - see: https://github.com/bitwarden/directory-connector/pull/93.
Ultimately, the solution was to pass a flag …

Don't check user group filter for deleted users

---

src/app/services/services.module.ts
src/app/tabs/more.component.ts
src/bwdc.ts
src/program.ts
src/services/ldap-directory.service.ts

I added some breaking changes to jslib https://github.com/bitwarden/jslib/pull/332, bumping jslib to resolve this issues for everyone else.

[Chore] Bump jslib

---

package-lock.json
package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/services/services.module.ts

Remove the last remnants of the dead analytics code.
Depends on https://github.com/bitwarden/jslib/pull/345

Remove dead code

---

src/package.json

> Version bump in preparation of general release
- **src/package.json**: Bump version from 2.9.1 -> 2.9.2

[Version] Bump to 2.9.2

---

src/program.ts

Required to support https://github.com/bitwarden/jslib/pull/388.
jslib will need to be merged & bumped first.

Add --cleanexit option

---

src/package.json

> Bump version for upcoming release from `2.9.2` -> `2.9.3`
- **src/package.json**: Bump version

[Version] Bump to 2.9.3

---

src/app/services/services.module.ts
src/bwdc.ts
src/services/api.service.ts
src/services/auth.service.ts
src/services/nodeApi.service.ts
src/services/sync.service.ts

Bumps jslib to support the changes in bitwarden/jslib#435

Add support for helpers in environment service

---

src/services/azure-directory.service.ts

https://docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-1.0#list-member-objects

Update Administrative Units API Endpoint

---

src-cli/package.json
src/package.json

Note: this will be cherry picked to `rc`

Version bump to 2.10.0

---

.github/workflows/build.yml
.github/workflows/release.yml

These changes were based off the linter output.

Update workflows with linter suggestions

---

src/package.json

Bumping version to 2.9.6
Will need to be cherry-picked into `rc`

Version bump to 2.9.6

---

.github/workflows/build.yml

Fix the ELF header issue in the Linux CLI reported in https://github.com/bitwarden/directory-connector/issues/146. 
* **.github/workflow/build.yml:** Split out the cli build onto their respective platforms.
- Added simple automated testing to each of the new build jobs to make sure the resulting executable runs without errors.

Fix for Linux cli ELF header issue

---

src/package.json

Version Bump 2.9.8

---

package-lock.json
package.json
src/app/accounts/apiKey.component.ts
src/app/app.component.ts
src/app/services/services.module.ts
src/app/tabs/settings.component.ts
src/bwdc.ts
src/main.ts
src/program.ts
src/services/ldap-directory.service.ts
tslint.json

Removes the allow-empty-catch exception in tslint and adds logging to most of the catch statements. This is to avoid quietly swallowing errors which makes it difficult to debug errors.
* **jslib:** Updated submodule to https://github.com/bitwarden/jslib/commit/f09fb69882525b3be7b2e257e7723eeb79b343d1
* **app/app.components.ts:** Pass logService into constructor and log error on catch
* **app/accounts/apiKey.components.ts:** Pass logService into constructor and log error on catch
* **app/tabs/settings.components.ts:** Pass logService into constructor and log error on catch
* **app/services/services.module.ts:** Fix build error after updating of jslib: Created missing policyService
* **services/ldap-directory.service.ts:** Log error on catch
* **src/main.ts:** Log error on catch
* …

Remove empty catch blocks and remove allow-empty-catch tslint rule

---

package-lock.json
src/app/services/services.module.ts
src/bwdc.ts
src/services/auth.service.ts
src/services/azure-directory.service.ts

Bump jslib and update to electron 14.2.0
* **jslib:** Pull in newest changes to jslib
* **package-lock.json:** Changes after running `npm i`
* **services/auth.service.ts:** Added missing dependency param `CryptoFunctionService` for ctor of `AuthServiceBase`
* **bwdc.ts:** Added `CryptoFunctionService` to ctor of `AuthService`
* **app/services/services.module.ts:** Added `CryptoFunctionService` to ctor of `AuthService`
Usual regression testing
- Still two issues that actually should be ignored console.error in `azure-directory.service.ts` and a equality-check in `sync.services.ts`

Update electron to 14.2.0

---

src/app/app.component.ts
src/app/services/services.module.ts
src/app/tabs/dashboard.component.ts
src/app/tabs/more.component.ts
src/bwdc.ts
src/program.ts
src/services/auth.service.ts
src/services/sync.service.ts

We currently initialize all our services manually in `ServicesModule`. This makes it a bit cumbersome since we have to define everything in order, and should make it easier to detect bad patterns like circular dependencies.
Depends on: https://github.com/bitwarden/jslib/pull/565.
We should be a bit vigilant during regression testing and verify everything works. Since I don't have a directory connector instance set up.

BEEEP: Refactor services DI

---

.github/workflows/version-bump.yml

Fix typo in Version Bump workflow
* **.github/workflows/version-bump.yml:** Fix typo in Version Bump workflow

Fix typo in Version Bump workflow

---

.github/workflows/release.yml

Adds workflow inputs and logic to skip the version check if the pipeline run is a redeployment.
- **.github/workflows/release.yml** Added workflow inputs and logic for version check step.

Added logic for redeployments

---

package.json

As the year 2022 has arrived it's time to update our copyright in various places.
Asana task: https://app.asana.com/0/0/1201609982295261/f
- **package.json:** Update year in copyright to 2022
Nothing really to test here other than to verify we show the current year in the copyright.

Update year in copyright

---

src/services/stateMigration.service.ts

Update jslib. This will pull in the following new commits:
* `2341b19` Fix "no amr found" error in bwdc cli (bitwarden/jslib#589)
* `4074c2a` [Bug] [Account Switching] Ensure EnvironmentUrls Pull From The Correction Location On Account Add (bitwarden/jslib#602)
* `def3c47` Disable spell checking (bitwarden/jslib#601)
* `57d60bd` Misc Account Switching Fixes & Refactors (bitwarden/jslib#600)
* `c6f20f8` Fix prettier (bitwarden/jslib#598)
* `c27fc39` Use correct api Keys (bitwarden/jslib#599)
* `cc989e4` Rename all occurances of fb to formBuilder (bitwarden/jslib#595)
* `e4cd0af` [bug] Add several state value defaults (bitwarden/jslib#593)
* `d68c1da` Remove usage/detection of NativeScript (bitwarden/jslib#566)
* `3d7b427` Use MP policies when registering a new user through SSO …

Update jslib and minor fixes for account switching

---

.github/workflows/version-bump.yml

Updates the `Version Bump` action to the latest version.
- **.github/workflows/version-bump.yml:** Updates the `version-bump` action to the latest hash.

Update Version Bump action to latest

---

package-lock.json
package.json
src-cli/package-lock.json
src-cli/package.json
src/package-lock.json
src/package.json

Rename package to `@bitwarden/directory-connector`.

Rename package to @bitwarden/directory-connector

---

package.json

In #207 we renamed the package, but we had build issues in desktop. To ensure this change doesn't cause any potential issues, I've added the same fix to directory connector.

Fix scoped package name

---

src/app/accounts/apiKey.component.html
src/app/accounts/environment.component.html
src/app/tabs/dashboard.component.html
src/app/tabs/more.component.html
src/app/tabs/settings.component.html
src/app/tabs/tabs.component.html
src/index.html
src/scss/plugins.scss
src/scss/styles.scss

> Update all `directory connector` classes to use the new `bwi` font sheet
> All styles/classes have been updated to reference the new font sheet.
* Test all icon locations to make sure a similar experience occurs (no major changes - all icons are working as expected)
* [Jslib - Icons - Update Font Sheet](https://github.com/bitwarden/jslib/pull/582)

[Icons] Update Font Sheet

---

webpack.renderer.js

It seems the `dot` is included in `[ext]`. Removed the duplicate.

Fix webpack using double dots

---

src/app/services/services.module.ts
src/bwdc.ts
src/main.ts
src/services/state.service.ts

Updates jslib and updates StateService and StateMigrationService inits to account for parameter changes

[chore] Update jslib

---

src/app/services/services.module.ts
src/bwdc.ts

Companion PR to https://github.com/bitwarden/jslib/pull/651.

Client & Version headers

---

README.md

> Update all `help.bitwarden.com` and `bitwarden.com/help/article/*` to the new `bitwarden.com/help/*` URL pattern
- **README.md**: Updated URL to new pattern
- [jslib - [Help] Update links to new pattern](https://github.com/bitwarden/jslib/pull/658)
- Make sure URL links don't 404 and take you to the correct page

[Help] Update links to new pattern

---

.github/workflows/enforce-labels.yml

Adds Hold label enforcement as done in bitwarden/cli#456

Enforce Hold label

---

.github/workflows/release.yml

We would like the ability to test the majority of the functionality of our release pipelines so that we can release faster.
* **.github/workflows/release.yml:** Adds dry run options and gates. Updates action versions, which is a good test for dry-run

Added dry run logic

---

.github/workflows/release.yml

Rename `hotfix` release branch name to `hotfix-rc` to avoid branch name collisions with branches like `hotfix/this-feature`.
- **.github/workflows/release.yml** rename `hotfix` to `hotfix-rc`

Update hotfix release branch name to hotfix-rc

---

.github/workflows/build.yml

Updating the old actions to their newest version.
- **.github/workflows/build.yml:** Updated actions to their newest version. Applied linting suggestions for some some `run:` steps.

Updated actions & applied linting

---

.github/workflows/build.yml

This PR fixes the Node caching error `Some specified paths were not resolved, unable to cache dependencies.`
- **.github/workflows/build.yml:** Moved `checkout` steps before `Setup Node` steps.

Fix Node caching error

---

.github/workflows/build.yml

Adding a manual trigger to the build pipeline in the directory-connector project

Add manual trigger to build workflow

---

src/app/app.module.ts

SG-132
Update client to use the new `JslibModule`.
Depends on https://github.com/bitwarden/jslib/pull/733.
* remove any jslib modules from `app.module`, import `JslibModule` instead

[JslibModule] Refactor to use JslibModule

---

.github/workflows/release.yml

Bumping pinned commit of the download-artifact action to bypass the broken GitHub api
- **.github/workflows/release.yml:** bumped pinned commit

Bump pinned commit of download-artifacts

---

src/abstractions/state.service.ts
src/services/state.service.ts

See https://bitwarden.atlassian.net/browse/EC-182

[EC-182] Refactor StateService secrets handling

---

src/services/azure-directory.service.ts

> Administrative Unit `/members` API call only returns the first 100 values. Fix this issue by utilizing the `@odata.nextLink` property returned for results greater than the maximum returned size of 100.
> EC-250
- **azure-directory.service.ts:** Added `nextLink` looping to gather **all** results (>100) for administrative units members api call
- Ensure that all AU groups get synced when there are >100 available

[EC-250] AU group next link

---

.github/workflows/release.yml

In order to track which Jira issues are included in each deployment, we need to tie the release pipeline to Github deployments, which the Github for Jira integration will then tie to Jira deployments.
* **[release.yml](https://github.com/bitwarden/directory-connector/compare/ENG-71-add-deployment?expand=1#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34)** Added workflow steps to create a Github deployment and update the status to success or failure based on the job success or failure.

[ENG-71] Add deployments to release workflow

---

.github/workflows/build.yml

The GitHub action Azure Key Vault is being deprecated and will no longer be maintained. The outcome of the related spike offers a solution to implement as a drop-in replacement using bash and the Az CLI. All references for the `Azure/get-keyvault-secrets` action will need to be replaced with this bash step in all our workflows.

Update deprecated Azure Key Vault in workflows

---

.github/workflows/build.yml
.github/workflows/enforce-labels.yml
.github/workflows/release.yml
.github/workflows/version-bump.yml
.github/workflows/workflow-linter.yml

- Update all the workflow actions pinned versions
- .github/workflows/*

update all actions pin

---

.github/workflows/enforce-labels.yml

- Update all the workflow actions pinned versions
- .github/workflows/*

update enforce label action tag

---

.github/workflows/build.yml

Removes a .NET installation that isn't used.
- **.github/workflows/build.yml:** .NET setup removal; it's only used to print a version!

Remove .NET SDK usage

---

.github/CODEOWNERS

Make `team-admin-console-dev` the owners of directory-connector.

[AC-1291] Add CODEOWNERS file

---

README.md

Mentions Node 18 since that's the LTS we use now.
- **README.md:** Version change.

Mention Node 18

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/version-bump.yml
.github/workflows/workflow-linter.yml

- To update all the repository workflow to use latest actions
- **.github/workflows/*:** Update the workflows

[DEVOPS-1403] - Update all workflow

---

.github/workflows/build.yml
.github/workflows/enforce-labels.yml
.github/workflows/release.yml
.github/workflows/version-bump.yml

This PR updates all of the workflows in this repository to our current standard.
- **.github/workflows/build.yml:** Update runners to latest tagged version. Update all action hashes to latest versions. Fix warning on GitHub outputs. Update commands. Move `NODE_OPTIONS` environment variables to job `env` key to remove errors.
- **.github/workflows/enforce-labels.yml:** Update runners to latest tagged version.
- **.github/workflows/release.yml:** Update runners to latest tagged version.  Update all action hashes to latest versions. Fix warning on GitHub outputs. Apply linter suggestions.
- **.github/workflows/version-bump.yml:** Update runners to latest tagged version. Update all action hashes to latest versions. Apply linter suggestions.

Update workflows to current standard

---

.github/workflows/build.yml

This PR fixes the generation of checksum artifacts.
- **.github/workflows/build.yml:** Switch from `sha256sum` to `shasum` due to the prior command being missing on the `mac-os` runner.

Build workflow - Fix checksum generation

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/version-bump.yml

```
```
This PR updates all of our action versions to reference `main` instead of `master`.
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

---

.github/workflows/build.yml

This PR updates the way we install the AST in our Build workflow.  This new version is now on .NET 6 which is still supported.
Run: https://github.com/bitwarden/directory-connector/actions/runs/6949320462
- **.github/workflows/build.yml:** Change install from action to single command.

Update AST in Build workflow

---

.github/workflows/workflow-linter.yml

This PR updates our workflow call for the `workflow-linter` to `main`.
- **.github/workflows/workflow-linter.yml:** Update `workflow-linter` from hash to `main`.

Update workflow call to use main branch

---

src/package.json

Reverts bitwarden/directory-connector#387

Revert "Bump version to 2023.12.0"

---

package-lock.json
package.json

As part of a dependency audit of the project this PR updates dotenv to `v16.4.1`
* Upgrade `commander` to `v11.1.0`

Upgrade dotenv (v9.0.2 ⮕ v16.4.1) 

---

package-lock.json
package.json

As part of a dependency audit of the project this PR updates lint-staged to `v15.2.0`
* Upgrade version in `package.json`

Upgrade lint-staged (v12.5.0 ⮕ v15.2.0)

---

package-lock.json
package.json

As part of a dependency audit of the project this PR updates `copy-webpack-plugin` to `v12.0.2`
* Upgrade version in `package.json`

Upgrade copy-webpack-plugin (v11.0.0 ⮕ v12.0.2) 

---

.github/workflows/version-bump.yml

```
```
This PR fixes the `while` loop logic for verifying the version has updated.
* **.github/workflows/version-bump.yml:** Fix `while` loop logic.
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

Version Bump workflow - Fix while loop logic

---

.github/workflows/build.yml

This PR adds back the `push` trigger in order to make sure builds are up-to-date after version bumping for release.
- **.github/workflows/build.yml:** Add `push` trigger for `main`, `rc`, and `hotfix-rc` branches.

DEVOPS-1907 - Add push trigger to Build workflow

---

.github/workflows/version-bump.yml

```
```
Add a new parameter to whether to send a notification for upcoming releases, which must be disabled by default.
Related PR: https://github.com/bitwarden/devops/pull/2329
* **.github/workflows/version-bump.yml:** Add new input
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

BRE-87 ADD: Slack notification enable feature and check in version-bump workflow

---

.github/workflows/build.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-69)
- To upgrade macOS runner to 13
- **.github/workflows/build.yml:** To upgrade macOS runner to 13

[BRE-69] - Upgrade to Macos-13 Runner

---

.github/workflows/scan.yml

[PM-7288](https://bitwarden.atlassian.net/browse/PM-7288) - Deploy scanning workflow organization wide
[PM-7288]: https://bitwarden.atlassian.net/browse/PM-7288

Include action to support Checkmarx and Sonar

---

.github/PULL_REQUEST_TEMPLATE.md

Update the PR template to use the [template in the template repository](https://github.com/bitwarden/template/blob/main/.github/PULL_REQUEST_TEMPLATE.md). template template template
I removed a reference to feature flags in the "Reminders before review" section because we don't use them in this repository. Otherwise it's a straight copy/paste.

Update PR template from template repo

---

.gitignore
jslib/angular/src/services/jslib-services.module.ts
src/app/services/injection-tokens.ts
src/app/services/safe-provider.ts
src/app/services/services.module.ts

https://bitwarden.atlassian.net/browse/AC-3033
Add `safeProvider` to this repository so that we have typesafety in our Angular DI. See https://github.com/bitwarden/clients/pull/8206 for more info about this original work.
This will help us refactor and maintain this repository.
- ❓ (`:question:`) for …

[AC-3033] Add SafeProvider

---

.github/workflows/version-bump.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-246)
- Use GH app as auto PR creator
- 🎨 (`:art:`) for suggestions / …

[BRE-246] - Use GH-App for version bump workflow

---

src/app/tabs/settings.component.html
src/locales/en/messages.json

[PM-11293](https://bitwarden.atlassian.net/browse/PM-11293)
Change verbiage for the overwriting syncs option, moves checklist item, and adds a tool tip link.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …

[PM-11293] Add warning message and help icon to sync option

---

.github/workflows/version-bump.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-405?atlOrigin=eyJpIjoiNDhjN2UyOTU1MjAwNDAzOWI1ZmQ4YTM5OGE3NDM1YzkiLCJwIjoiaiJ9)
This PR updates the `Version Bump` workflow so our GitHub App `BW-GHApp` can push directly to `main` for updating the product version.
- [Tested here](https://github.com/bitwarden/directory-connector/actions/runs/11617011616)
- 📝 (`:memo:`) …

BRE-405 - Update Version Bump workflow to push directly to main

---

package.json

> Version Bump in preparation for January release
- ❌ (`:x:`) or ⚠️ …

Version bump to 2025.1.0

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/test.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-549?atlOrigin=eyJpIjoiNjA1MWM4MmRlZjcyNDhkMWIzNDg0YzBjNGIzZGJjZWIiLCJwIjoiaiJ9)
This PR adds in the `rc` branch logic that was previously removed.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

BRE-549 - Add rc branch logic

---

.github/workflows/integration-test.yml
.github/workflows/test.yml

https://bitwarden.atlassian.net/browse/VULN-127
Codecov updated the codecov/codecov-action GitHub action. In this new version, it no longer requires a CODECOV_TOKEN in the workflows. This PR will update the action to t
he current latest version (5.1.2) and remove the CODECOV_TOKEN for the action.
Note: The codecov/test-results-action GitHub action still requires a token, and can not be removed yet.
- 👍 (`:+1:`) …

Updated Codecov action and removed token

---

.github/workflows/integration-test.yml
.github/workflows/test.yml

https://bitwarden.atlassian.net/browse/VULN-202
Remove the check for secrets. Replace with logic to identify if the code is running in a fork.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …

Remove secret check for tests

---

package.json

> Prepare for next release by bumping version to **2025.3.0**
- ❌ (`:x:`) …

Version bump to 2025.3.0

---

.github/workflows/integration-test.yml
.github/workflows/test.yml

Internal change.
Removes the Codecov token which is no longer needed to upload results.
- 🎨 (`:art:`) for suggestions / …

Remove references to Codecov token

---

package.json

N/A
Bump the version to 2024.4.0.
Note that this is effectively a re-release of 2025.1.0 in order to rollback from defective release 2025.3.0. `rc` will branch from 2025.1.0 and have this cherry-picked into it.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …

Bump version to 2024.4.0

---

.github/workflows/build.yml

[BRE-773](https://bitwarden.atlassian.net/browse/BRE-773)
Using new windows certificate for signing
- 🎨 (`:art:`) for …

[BRE-773] Fixing windows signing cert

---

package.json

> Bump version to `v2025.5.0` in preparation for release
- ❌ (`:x:`) or ⚠️ …

chore: bump version to v2025.5.0

---

src/services/batch-request-builder.ts
src/services/sync.service.ts

https://bitwarden.atlassian.net/browse/PM-21614
Fixes issue where disabling groups or users during import would cause an undefined error.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …

[PM-21614] Fix null error

---

package-lock.json
package.json

https://bitwarden.atlassian.net/browse/PM-20726
As far as I can tell, this can be removed as we don't use it in the app. Other dependencies list is as a sub-dependency (at their own versions) which should be all we need. (This is also done the same way in `clients`)
- …

[PM-20726] Remove minimatch dependency

---

package.json

> Bump version in preparation for release
- ❌ (`:x:`) or ⚠️ (`:warning:`) …

Bump version to v2025.6.1

---

package.json

> Bumping version in preparation for the `v2025.9.0` release
- ❌ (`:x:`) or …

chore: bump version to v2025.9.0
