bitwarden/directory-connector

package-lock.json
src/services/azure-directory.service.ts

As discussed with the support e-mail, I am creating a pull request to allow filtering users coming from Azure AD based on their group membership.
Basically, back-compatibility with existing filtering is still kept which means that tenants who use the `include:` and `exclude:` keywords will still work fine. I added two keywords `includeGroup:` and `excludeGroup:` which should contain the group ID from Azure Active Directory. With each member found, the Graph endpoint [checkMemberGroups](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_checkmembergroups) is called and based on the query result the user is included or excluded.
This PR allows for better synchronization use in environments which have a lot of users including service accounts, B2B guest users etc. …

Add support for filtering users based on their group membership

---

src/app/tabs/settings.component.html
src/locales/en/messages.json
src/models/ldapConfiguration.ts
src/services/ldap-directory.service.ts

Fixes bitwarden/directory-connector#6
Enables support for STARTTLS on plain LDAP connections, with some UI changes to accommodate both encrypted connection types.
STARTTLS. 
LDAPS.

starttls: Support LDAP STARTTLS

---

src/app/tabs/settings.component.html
src/app/tabs/settings.component.ts
src/locales/en/messages.json
src/models/ldapConfiguration.ts
src/services/ldap-directory.service.ts

Some LDAP servers have paging turned off. If so, this can cause an error since we made the assumption that all servers are using paging. This change lets the user control that through the settings. This can also be set in the data.json file under directoryConfig_0 > pagedSearch.
For example:
"directoryConfig_0": {
...,
"pagedSearch": true
},

Added option to let user control the paged param

---

src/services/gsuite-directory.service.ts

Users of a group can have roles of owner, manager, and member. Not sure why we were only allowing members to filter through before. We've had a few customers complaining about this. This PR allows all members to be part of the synced group.

include all members of the g suite group

---

src/app/tabs/settings.component.html
src/services/onelogin-directory.service.ts

OneLogin users may not have a valid email address in the `email` field. According to our customers, a valid email address could also come from the `username` field. Finally, we also fall back to trying to form an email address using the `useEmailPrefixSuffix` sync setting, if enabled.

add support for email coming from username prop

---

src/services/azure-directory.service.ts
src/services/baseDirectory.service.ts
src/services/gsuite-directory.service.ts
src/services/okta-directory.service.ts
src/services/onelogin-directory.service.ts

This PR fixes a bug where disabled users were not being considered in the `filterUsersFromGroupsSet` function. We would only want to skip disabled users from this filter if we're using the `removeDisabled` setting, which treats disabled users the same as deleted users.

dont skip disabled users if not removeDisabled

---

scripts/notarize.js
src/app/accounts/set-password.component.html
src/app/accounts/set-password.component.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/services/services.module.ts
src/locales/en/messages.json
src/scss/bootstrap.scss
src/scss/misc.scss

> Added the sso set password flow into the directory connector. Make sure password validation is in place and that a successful update lands you on the dashboard page.
- **jslib**: Update from 5d874d0 to 6ab444a
- **set-password.component.html**: Created UI (similar to boostrap'd web layout)
- **set-password.component.ts**: Added class to handle set password flow. Updated success route to land on the dashboard. Added password strength local functions.
- **app-routing.module.ts**: Added `set-password` for routing capabilities
- **app.module.ts**: Added `set-password` component for compilation/use
- **services.module.ts**: Added `policy.service` provider (needed for enforcing policy options within super class `change-password`)
- **messages.json**: Added all missing strings
- **misc.scss**: …

[SSO] Added set password flow

---

src/app/accounts/two-factor.component.ts

>When logging in with SSO in the Directory Connector from a user account that has 2FA enabled the 2FA code input page does not close on successful validation. Additional details [here](https://app.asana.com/0/1188746734054362/1192839560133337)
1. Log in to Directory Connector via SSO with a user account using 2FA
2. Enter the validation code from your 2FA app and click submit
3. The 2FA validation screen will not close unless "Cancel" is clicked. 
- **two-factor.component.ts**: Adjusted where we set the success route to be after `super.ngOnInit()`.

[SSO] Adjusted 2fa success route

---

src/app/accounts/two-factor.component.ts

> Fix issue with 2fa not redirecting after successful response
- **two-factor.component.ts**: Added await for `ngOnInit` in order to make sure we properly set the success route.

[SSO] Bug - Added await to prevent race condition for successRoute

---

src/app/accounts/two-factor.component.ts

> Currently, when a new bitwarden/org user is created, they are given a status of accepted. This can create issues for organizations trying to confirm the same user (which can't happen until they've set their master password). To alleviate the issue, change new user's orgUser status to invited until after they've set a master password.
- **jslib**: Update from 5e0a2d1 to d84d6da
- **two-factor.component.ts**: Update import/constructor to pass in active route

[SSO] New user provision flow jslib update (5e0a2d1 -> d84d6da)

---

src/bwdc.ts

Adds ability to get to next steps on #41 ; `jslib` update to commit hash is from https://github.com/bitwarden/jslib/pull/188
Add logging to the bwdc when initializing it's lowdb storage service so any failures, issues, warning, etc. which may result in wiping of the data file (`data.json`) will get appropriately logged for further troubleshooting.
The resulting output, for example, if there's a syntax error (or other error) with the existing `data.json` file may look like this:
```bash
$ node bwdc.js login
Error creating lowdb storage adapter, "Malformed JSON in file: /Users/<user>/Library/Application Support/Bitwarden Directory Connector/data.json
Unexpected token h in JSON at position 303"; emptying data file.
```

Add logger to lowdb storage service

---

package.json

Hi,
As per requested by @cscharf - This PR is raised to bump a NodeJS dependency (`https-proxy-agent`) which solves an upstream bug in the [CLI repo](https://github.com/bitwarden/cli/issues/181). 
The bug in question prevents you from log in successfully when running CLI commands behind an HTTP proxy.

Bump https-proxy-agent dep. to 5.0.0

---

package.json

I had prematurely accepted a package version update of https-proxy-agent which then broke the build via a TypeScript compile error on that dependency.

Revert https-proxy-agent version

---

src/commands/config.command.ts
src/program.ts

Bitwarden Directory Connector currently only accepts passwords interactively or on the command line. Interactive input is not always possible (running in automated systems) and command line is insecure, since the value is then available to all other processes on the same host via process listing. Most programs that require secrets to be input solve this by allowing to set the password in a file that can be appropriately protected or in an environment variable that can be programmatically set so that it is not revealed in a process listing.
Forum entry for the PR here: https://community.bitwarden.com/t/bitwarden-directory-connector-accept-passwords-from-files-or-environment-variables/16319

Add options for giving passwords and secrets as file contents or in an environment variable

---

package-lock.json
package.json
tsconfig.json

Bump `https-proxy-agent` to v 5.0.0 per the discussion [here](https://github.com/bitwarden/cli/issues/181).
Bump of dependencies in `package.json` and `package-lock.json`.

Bump https proxy agent

---

src/services/azure-directory.service.ts

Customer was reporting that graph API calls were failing, which were being caught here and causing the user to not be filtered out of the synced result set. This allows the API call failure to propagate out further and return an error to the end user.

dont catch api error and return false

---

src/services/ldap-directory.service.ts

Node had a bug which would reject public certificates as empty if their subject was empty, even if they had altNames defined. See https://github.com/nodejs/node/pull/22906.
This bug was fixed in node 12.14.1. Our electron version uses a later node version, so it doesn't affect the electron app.
However, the `bwdc` CLI uses the locally installed node version, so users on older node versions are still susceptible.
The bug resides in node's TLS `checkServerIdentity` function. We can provide our own `checkServerIdentity` function in the `ldapjs` client options. Our function works by inserting a non-null subject line before calling the standard function.
This is based on auth0's workaround which I have referenced in the comment. (Let me know if this is unnecessary.)
This now correctly …

Fix handling of empty subject names in certs

---

src/services/sync.service.ts

While working on bitwarden/server#1101 I found another place where an email's length is checked.
I encountered a faulty behaviour though, while checking the method [filterUnsupportedUsers in syncService.ts](https://github.com/bitwarden/directory-connector/blob/61c6ba81894fb6162cd51d26eb542fb616cf7a29/src/services/sync.service.ts#L106) 
Also check [jsFiddle](https://jsfiddle.net/1t89mou6/37/) for test cases
Finally, I extended the filter to handle emails with up to 256 chars

Fix filteringForUnsupportedUsers and extend email validation to handle emails up to 256 char

---

src/services/sync.service.ts

Fix a bug that prevented AD users from being removed from their Bitwarden organization.
The steps to reproduce the bug are:
1. User is not in Bitwarden
2. User is created in AD (not Azure AD)
3. User is added to the AD Group, "APP_Bitwarden_TEST"
4. BWDC (Electron app) is configured to sync with a User filter of `memberof=cn=APP_Bitwarden_TEST` and with `overwriteExisting=true`.
5. BWDC syncs, finds the new user, sends a user invitation
6. User creates account, accepts invite, and admin confirms
8. User is removed from AD Group, "APP_Bitwarden_TEST"
9. Test BWDC sync - the filter should not pick up ANY users, disabled users, deleted users or groups. If any of these are present then this issue will not occur.
10. BWDC syncs - says that it syncs 0 users and 0 groups. The user is NOT removed …

Fix AD sync not overwriting removed users

---

src/app/tabs/dashboard.component.html

When clicking the start or sync buttons angular casts a `ExpressionChangedAfterItHasBeenCheckedError` error. This seems to be caused by the elements referring to themselves using the `appApiAction` directive. By wrapping the buttons in forms and attaching the event to the forms we avoid this error.

Resolve ExpressionChangedAfterItHasBeenCheckedError

---

package-lock.json
package.json

In March 2019, we forked `ldapjs` in order to fix support for node 10 ([here](https://github.com/bitwarden/directory-connector/issues/13)). `ldapjs` added support for node 10 in August 2019 ([here](https://github.com/ldapjs/node-ldapjs/issues/524)). We should revert to using the official package and bump it to its latest version.
I've done the following for basic testing:
* reviewed release notes for any breaking changes ([here](https://github.com/ldapjs/node-ldapjs/releases)) - although these are very brief
* built the project and performed a test sync with a Jumpcloud instance
I specified the current version of `ldapjs` in `package.json` without using `^` or `~` modifiers. I'm not sure if we have any recommended practice around this.
I also updated `@types/ldapjs` to the current …

Update ldapjs dependency

---

.github/workflows/build.yml
.github/workflows/release.yml

This pins all action versions in the workflows to commit hashes. This protects us from any malicious changes to the actions in case people force push tags.

Pin versions of actions in workflow

---

src/app/tabs/settings.component.html
src/commands/sync.command.ts
src/models/syncConfiguration.ts
src/services/sync.service.ts

Related to bitwarden/server#1311. Allows import of large numbers of users and groups. Also add orgId to last sync hash.
* **settings.component.html**: Add `largeImport` checkbox button. Formatting changes.
* **sync.command.ts**: remove unneccessary using
* **syncConfiguration.ts**: Add largeImport
* **sync.service.ts**: specify largeImport. Add orgId to last sync hash. This resolves issue where changing the organization synced to would not update until directory changes exist.

Add option to bypass large import limit of 2000 users

---

src/app/tabs/settings.component.html
src/locales/en/messages.json

Closes https://app.asana.com/0/1153292148278596/1199515611430068/f.
One Login uses the Role concept instead of Groups for filtering bitwarden groups. This PR alters the language of our filters to Role rather than group

OneLogin uses Roles instead of Groups

---

.github/workflows/release.yml

In the DevOps retro, we identified that the release workflows of the clients should be programmatically constrained to the `rc` branch to protect from human error on release

constraining release to the rc branch

---

src/services/okta-directory.service.ts

Filter excluded/included groups as early as possible to avoid using up API calls and long waits.
We got some complaints concerning Okta-sync speed. Luckily the users have filters set, so we can improve things by filtering out groups earlier.
I also refactored the wait some to apply to `buildGroup` method. This saves us one wait, not a huge deal, but every bit helps 😃

Improve okta group performance

---

package-lock.json
package.json

Revert the update to the `ldapjs` dependency which I did [here](https://github.com/bitwarden/directory-connector/pull/111). The update appears to have broken syncing for some users. Reverting to our fork until we can diagnose the issue.
This will need to be cherry-picked to `rc` after merge.

Revert ldapjs update, use forked repo instead

---

src/app/services/services.module.ts
src/bwdc.ts
src/main.ts
src/services/api.service.ts
src/services/auth.service.ts
src/services/keytarSecureStorage.service.ts
src/services/nodeApi.service.ts

Linked to bitwarden/jslib#414
bitwarden/jslib#382 and bitwarden/directory-connector#121 switched authentication to organization API key flow. However, this authentication does not include refresh tokens.
This work extends `ApiService` to override the token refresh flow with the api key authentication flow.
* **services.module.ts/bwdc.ts**: Update services to new `ApiService`. `refreshToken` is a little wonky. A method is needed due to a circular dependency on `apiKeyService` and `authService` to perform the refresh. I'm exporting the method because I wanted a single code source, but `ApiService` is already split higher upstream, requiring both `ApiService` and `NodeApiService` to be extended. The Compromise is to define the method in one of the `api.service.ts` files and export it while …

Refresh token with api key

---

README.md

With @Hinton bumping node to 14 recently, I've adjusted the README to show the need for Node 14.17 (LTS)

Add node version to requirements in README.md

---

src-cli/package.json
src/package.json

2.10.0 is unreleased and should have been merely a patch bump from 2.9.3 since no features were added.
> Note: will be cherry picked to `rc`

Bump patch version to denote no features released

---

src/services/azure-directory.service.ts

Fix this behaviour, as requested by the good folks over in customer success:
>When configuring BWDC to use Azure Active Directory sync, and an invalid Application ID or Secret Key for the Azure AD auth is provided, BWDC displays an "unknown error has occurred" error card and does not log any network requests or errors on the console. BWDC should display "invalid AppID or secret key" instead.
In `azureDirectoryService.init()`, we define a callback which is responsible for authenticating and getting the access token. After its work is completed, it calls the `done` function with either an error or the access token.
It looked like we were doing this already, but we were getting stack traces rather than nice error messages, and that was changed to a generic error message by `appApiAction`. It …

Fix Azure client errors not displaying properly

---

src/bwdc.ts

Fixes https://app.asana.com/0/1169444489336079/1200917925520859/f.
The callback function was being called without a an appropriate bound `this` switching to an inline lambda fixes this issue.

Use inline closure to ensure `this` is defined

---

src/services/azure-directory.service.ts
src/services/sync.service.ts

We made some changes [here](https://github.com/bitwarden/directory-connector/pull/136) to throw an error if the directory service contains 2 or more users with the same email address. This is because we don't support duplicate email addresses in Bitwarden.
Some users have reported false positives, where the error was being thrown even though they didn't think that they had more than 1 user with the same email address.
I was able to reproduce this by simply disabling a user in Azure AD. This caused the disabled user to be returned by both the `getCurrentUsers` and the `getDeletedUsers` methods, which then caused the duplicate entry.
* `sync.service` - only throw an error if multiple `userEntry`s have the same email address but _different_ `externalId`s. `externalId`s should be unique to …

Ignore duplicate users with same externalId

---

.github/workflows/build.yml
.github/workflows/release.yml

The recent AST update broke functionality. Pinning the version to decrease attack surface of supply chain attacks as well as maintain stability in the pipeline. This has been done with the custom GitHub composite Action found at [bitwarden/gh-actions/install-ast](https://github.com/bitwarden/gh-actions/install-ast)

Switching the AST install to a custom composite action

---

.github/workflows/release.yml

Updating the cli job in the release workflow to skip the building and use the latest `rc` build artifacts instead

CLI release job update

---

src/app/tabs/settings.component.html
src/locales/en/messages.json
src/models/azureConfiguration.ts
src/services/azure-directory.service.ts

Add a selector to the AzureAD sync settings to let a user choose which Azure AD Identity Authority they want to use.
Further information on Azure Identity Authorities can be found [here](https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-plan-identity#choosing-your-identity-authority)
Asana task: https://app.asana.com/0/1169444489336079/1201382398383483/f
* **src/models/azureConfiguration.ts:** Extended the model to get/set the selected idendityAuthority
* **src/app/tabs/settings.component.html:** Added a dropdown to the Azure AD sync settings to select the Identity Authority 
* **src/locales/en/messages.json:** Added text for the label in the Azure AD sync settings
* **src/services/azure-directory.service.ts:** 
- Use new value from configuration to set the …

Add Azure Identity Authority Selector

---

src/services/ldap-directory.service.ts
src/services/sync.service.ts

Fixes an issue where a duplicate email error is being thrown. After a lot of investigation, the root cause of this has been determined to be deleted users; AD unfortunately allows emails to be duplicated for deleted users. Additional context here: https://app.asana.com/0/1169444489336079/1201410771133282/f
* **sync.service.ts** Add a condition to only add a user to the duplicateEmails array if the user is not deleted.
Please test around the syncing functionality and make sure that duplicates aren't flagged unexpectedly.
The change was done in a shared function in the sync service that all directory types use.
These are the expected outcomes when testing for duplicate emails:
- Two or more deleted users with the same email will not throw a duplicate email error.
- If an active user and a …

Don't flag deleted users as duplicates

---

package-lock.json
package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/tabs/dashboard.component.ts
src/app/tabs/more.component.ts
src/scss/plugins.scss

As a part of upgrading Angular, I noticed that the toaster library we use still depends on Angular 11. This PR replaces our current toaster library with `ngx-toastr`.
While at it, I replaced all direct calls to the library with `platformUtilsService.showToast` which will make it easier to do these changes in the future. (Please do not call the toaster library directly in the future!)
Depends on: https://github.com/bitwarden/jslib/pull/568
Removed toasterService from every component and used platformUtilsService instead. Note I didn't spend any time on formating the constructors since that will be a moot point soon.
Regression sweep to ensure toasts still behave correctly.

Replace toaster library

---

src/services/state.service.ts

Fix an issue after the state service refactor where directory settings were being cleared on logout from the cli.
[Asana task
](https://app.asana.com/0/1200804338582616/1201593355163718/f)
- **state.service.ts** Override `pushAccounts()` from jslib state service to not call `pruneInMemoryAccounts()`. This call was clearing the directory settings stored in the state. 
The reason we need to do this is because the CLI uses commands and is not like the other clients, so state service is inited on every call to a command.
There is a method called on the init of state service that is loadsStateFromDisk. In that method, when pushAccounts() is called, the user isn’t authenticated quite yet on login, so the account is deleted. Then the user is logged in and added to the accounts array, and boom …

override pushAccounts to not delete account from state

---

src/services/azure-directory.service.ts

Azure AD gets all users for an entire directory regardless of the user filters provided, and then sends a separate api request to Azure per user to determine group membership to filter out unwanted users. This takes an unnecessarily long amount of time for clients that only want to sync a few users and have many many more users in their directory.
With this change, if the `includeGroup` filter is provided, only the users that belong to that group are synced over. This eliminates the need to check group membership on a per user basis.
The `excludeGroup` filter process has also been changed. We now get the users from those groups and use that list to determine whether to filter out the users instead of making a call to get a user's group membership.
I also left the process for getting …

Only get users for includeGroup filter

---

package-lock.json

Bumping electron from 16.0.2 to 16.0.7
Depends on: https://github.com/bitwarden/jslib/pull/613
Asana task: https://app.asana.com/0/1200804338582616/1201660850797012/f
- **jslib:** Bump jslib to incorporate the changes made in https://github.com/bitwarden/jslib/pull/613
Regression testing on the settings UI

Bump jslib to include electron minor bump

---

src/app/services/services.module.ts
src/bwdc.ts
src/main.ts
src/models/account.ts
src/program.ts
src/services/state.service.ts
src/services/stateMigration.service.ts

* Duplicate PR: https://github.com/bitwarden/directory-connector/pull/211
* jslib update to storage schema: https://github.com/bitwarden/jslib/pull/611
* This PR split the "state" object in storage up into several top level account keys, a globals key, and an authenticatedAccounts key.
* jslib update to ensure data is properly migrated when there isn't an actively logged in account: https://github.com/bitwarden/jslib/pull/615
* This PR checked for a userId in storage, and if one isn't found saves all settings to a temporary key that are applied to the next authenticated account before being cleared.
* jslib update to fix key connector issues https://github.com/bitwarden/jslib/pull/616/files
Essentially this is just a jslib update for the directory connector. 
Some changes needed to be …

[chore] Update jslib & state services to match

---

src/services/auth.service.ts

https://app.asana.com/0/1201648796371593/1201694099230961
When logging out the process succeeds, but an error is logged to the console about not being able to clear tokens. 
* We are redundantly cleaning state twice right now, once in the [main logout function](https://github.com/bitwarden/directory-connector/blob/9e3d1caee4c8f986fb6acff0cff7fc2375c53491/src/bwdc.ts#L262-L265), and once in the DC extended auth service. This is resulting in the method being called twice for logouts, and the second time throws an error because it expects to have something to clean up. I removed the auth service call, though I think removing either would have the same effect.

[bug] Remove redundant state clean call

---

package-lock.json
package.json

Fix issue where testing and syncing with an ldap connection would sometimes spin forever. This is due to an outdated version of the ldapjs package that has had many updates since it was last updated in this project(in 2019). This is one of the issues I was seeing locally: https://github.com/ldapjs/node-ldapjs/issues/602
The version of ldapjs that was being used was a fork of the original package, and the fix implemented in the forked version has long been merged back to the original package: https://github.com/ldapjs/node-ldapjs/pull/497
[Asana Issue](https://app.asana.com/0/0/1201648363194411/f)
Fix has been confirmed to fix issue locally by QA
- **package.json** & **package-lock.json** Update ldapjs to get several bug fixes for the search function used for to get users and groups.
Test …

Update ldapjs to include fixes for syncing issues

---

package-lock.json
package.json
webpack.renderer.js

> Remove all instances of `FA`. Merge to both `master` and `rc` once approved.
- **package.json**: Removed `FA` node module from the web application
- **package-lock.json**: Updated due to `package.json` changes
- **webpack.renderer.js**: Exclude `bwi-font` instead of `FA`
-  Make sure the components listed above are working/looking as expected

[Icons] FF - old font cleanup

---

src/services/state.service.ts

Fix the following defect: when upgrading from the current release of d-c, logging in fails silently.
Asana: https://app.asana.com/0/1169444489336079/1201909137219813/f
d-c has its own account scaffolding method in `scaffoldNewAccountDiskStorage`, but it was calling `storageService.save` directly instead of using `saveAccount` in the base class. You must use `saveAccount`, because that deals with any stale disk cache (see https://github.com/bitwarden/jslib/pull/668). Otherwise, it writes the new value to disk but does not clear the old disk cache, and `stateService` methods continue reading the old cached values.
Regression testing on logging in:
* after upgrading
* on a fresh install (or after clearing data.json)
* in the gui and cli

Use saveAccount to scaffold new account

---

src/services/state.service.ts
src/services/stateMigration.service.ts

Syncing with the BWDC CLI on Windows was crashing.
https://app.asana.com/0/1201211497354246/1201885120581283
It was happening because the user and group deltas were previously stored in regular storage, not secure storage.
When we did the state service swap out, we accidentally put them in secure storage instead of regular storage. This worked fine on MacOS because keychain has a pretty large storage limit (4KB), but Windows credential manager has a much smaller limit (256 characters) and the value is exceeding it by a lot (about 3,500 characters, or 3.7KB). It also fails to save in the desktop app on Windows, but does so silently hence it wasn't causing the user to see it from what I can tell (the value is not stored at all in credential manager). We do not have control over the size of …

Move delta tokens out of secure storage

---

src/services/state.service.ts

[Context](https://bitwarden.atlassian.net/browse/EC-176)
Fixes syncing from the CLI would throw the error Cannot read properties of null (reading 'directorySettings') for some users. Determined that this was happening for people with server url's configured and that the CLI was getting the base url on the account level. We are never going to utilize separate accounts in the Directory Connector, override stateService.getEnvironmentUrls to only return the global ones.
- **src/services/state.service.ts:** Override state service to only use global environment urls

[EC-176] Fix CLI errors caused by server URLs

---

src/services/gsuite-directory.service.ts

Custom SDK query is used when filtering users, but not groups. This add the feature to groups as well.
It was either forgotten or maybe wasn't available at that time.
Docs will need to update to include the custom query for groups.
The change reuses code for filtering users and applies it for groups as well.

[PS-1212] GSuite: Use custom filter query when fetching groups.

---

.github/workflows/build.yml
src/services/keytarSecureStorage.service.ts

Fix the following bug:
1. log in to bwdc CLI
2. run `bwdc config directory 0`
3. observe error: `Password is required.`
This error is being thrown by keytar - "Password" is referring to the secret being saved in the keychain (not the user's password/api key).
Keytar throws if you try to save a falsy value. The config command basically loads and then re-saves all config settings, so any secrets that aren't explicitly set will be saved to the keychain as null values, triggering this error.
This was introduced with account switching. Before that, `setDirectory` checked for `null` and would call `secureStorageService.remove` instead. That check was removed.
- **src/services/keytarSecureStorage.service.ts** - check for null and call `remove` instead. By implementing it here we avoid this …

[EC-488] Handle falsy values in keytarSecureStorageService

---

src/services/gsuite-directory.service.ts

> For reasons unknown, empty query strings return a `400` for the `groups.list` Gsuite Directory API call. Therefore, in order to prevent issues retrieving groups, the API object is created and assigned a query **only if** the `query` is non-null
- **gsuite-directory.service.ts**: Separated `query` assignment into conditional statement
- Try standard `include/exclude` keywords for the `group filter`
- Try querying for a specific name `|name='Engineering'`
- Try both examples together
- Try an empty `group filter`

[EC-682] Adjust group query assignment

---

jslib/angular/src/components/callout.component.html
jslib/common/src/enums/importOptions.ts
src/app/tabs/dashboard.component.html
src/app/tabs/more.component.html
webpack.main.js
webpack.renderer.js

Directory-connector was upgraded to Angular v15 and the electron build has stopped working since.
This PR fixes that by adding a missing webpack config.
- **webpack.renderer.js:** Added required webpack configuration
- **jslib/angular/src/components/callout.component.html:** Ran prettier
- **jslib/common/src/enums/importOptions.ts:** Ran prettier
- **src/app/tabs/dashboard.component.html:** Ran prettier
- **src/app/tabs/more.component.html:** Ran prettier
Test that both the CLI and the App work as expected.

[AC-1614] Updated webpack config

---

.depcheckrc
package-lock.json
package.json
src/global.d.ts
webpack.renderer.js

As part of an initiative to audit dependencies across Directory Connector it makes sense to clean up a few unused packages from `package.json`.
Directory Connector has a handful of completely unused packages. Some seem outdated, and some don't really make sense as to why there were ever here at all. A node dependency check tool called [`depcheck`](https://github.com/depcheck/depcheck) reports the following unused dependencies on `main` when running its default command `depcheck`:
```
Unused dependencies
* @angular/cli
* duo_web_sdk
Unused devDependencies
* @types/jest
* css-loader
* html-loader
* node-loader
* nodemon
* prebuild-install
* sass
* sass-loader
* tapable
* ts-loader
* ts-node
* tsconfig-paths
* ttypescript
* typemoq
* webpack-cli
* jest-junit
Missing dependencies
* …
```

[AC-1743] pt. 3 ⮕ Remove unused packages

---

package-lock.json
package.json

As part of a dependency audit of the project this PR updates html-loader to `v5.0.0`
* Upgrade version in `package.json`

Upgrade html-loader (v3.1.2 ⮕ v5.0.0)

---

package-lock.json
package.json

As part of a dependency audit of the project this PR updates `typescript-transform-paths` to `v3.4.6`
* Upgrade version in `package.json`

Upgrade typescript-transform-paths (v2.2.4 ⮕ v3.4.6)

---

package-lock.json
package.json
src/program.ts

As part of a dependency audit of the project this PR updates prettier to `v11.1.0`
* Upgrade `commander` to `v11.1.0`
* Address one breaking change: the default import from `commander` has been removed.

Upgrade commander (v7.2.0 ⮕ v11.1.0)

---

.github/workflows/version-bump.yml

```
- [] New feature development
```
Report upcoming release to Slack using the generate version bump by the workflow.
Related PR: https://github.com/bitwarden/gh-actions/pull/281
* **.github/workflows/version-bump.yml:** Add step to report upcoming release
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

BRE-40 Add step to report upcoming release version to Slack

---

src/services/gsuite-directory.service.ts

https://bitwarden.atlassian.net/browse/AC-1716
Some customers report sporadic and non-identifiable errors syncing from gsuite that result in full directory wipes.
This is a risk when using the override setting, but is an issue that could be handled better in this case by directory connector.
This PR adjusts the gsuite service to throw an error if the member search endpoint throws. This lines up with the way we handle all other queries in this service, and from testing does not appear to break syncing in any other ways.
- Protected functional changes with optionality (feature flags)
- CI …

Throw an error if the gsuite member query fails

---

.github/CODEOWNERS
.github/renovate.json

Uses our standard Renovate configuration, with corresponding ownership so that these get more noticed.

Use latest Renovate config

---

src/services/ldap-directory.service.ts

https://bitwarden.atlassian.net/browse/PM-10380
Directory Connector is deleting existing users even without the "Overwrite existing users" flag set. This happens for Active Directory configurations that have the Active Directory "Recycle Bin" enabled. This is a very specific and IdP configuration related bug, and so has probably flown under the radar for some time.
This issue is caused because Directory Connector always checks for deleted users for Active Directory configurations, even with a live sync without the overwrite flag set. Adding a condition to the `getUsers` query for LDAP that returns early before searching for deleted users if the the sync is non-test and the overwrite flag is not set allows the users to come through in reports of a test sync, but stops them from being …

Filter out deleted AD users unless otherwise instructed

---

.github/workflows/scan.yml

Don't scan on nonexistent RCs

---

.github/workflows/build.yml
scripts/notarize.js

- [Card](https://bitwarden.atlassian.net/browse/BRE-264?atlOrigin=eyJpIjoiMTQ1YWRiODI0YzY3NDUxNzhlNDRmNzY3NDM3NzMxY2YiLCJwIjoiaiJ9)
This PR update the `build` workflow to use an API key for App Store Connect.
- **.github/workflows/build.yml:** Add setup for private auth key and update environment variables for building application
- **scripts/notarize.js:** Update logic to use API key if environment variables are set.

BRE-264 - Update build workflow to use API key for App Store Connect

---

.github/workflows/test.yml
jest.config.js
package-lock.json
package.json

Adds Codecov for collecting coverage and results information.

Configure Codecov coverage and results

---

package.json

The npm version was previously set to `~10.4`, but there is no node/npm release that satisifed the constraint of node `~18` and npm `~10.4`.
Set the `npm` version to `~10`. This change follows the approach in the main `clients` repository, where we accept minor version releases of node and npm.

Specify npm version ~10

---

.github/renovate.json

The renovate config in this repository groups patch and minor updates together. I think this is unhelpful as it has led to this enormous PR (which is failing): https://github.com/bitwarden/directory-connector/pull/353.
I'd rather smaller, easier PRs, even if we have many of them. We don't use this grouping in `clients` either.
The proposal here is to remove this grouping (this PR) and then force renovate to create new update PRs for each dependency (not sure how to do this - @withinfocus?).
@withinfocus renovate is your area, do you have any feedback on this approach? 
@bitwarden/team-admin-console-dev this is going to affect the team, so feedback welcome.

Remove npm minor grouping from renovate config

---

src/services/ldap-directory.service.ts

https://bitwarden.atlassian.net/browse/PM-13007
Fix the following bug from #641. When performing multiple syncs with an Active Directory server, QA received the following error:
> [Error] An item with the same key has already been added. Key: ----
It was also noted that:
> Per the payload BWDC sent over. All of the groups + users have an externalId of ----
Active Directory uses the `objectGUID` attribute value as the `exteranlId`. It is sent as a buffer, but ldapts treats all attributes as strings unless told otherwise. This mismatch meant that our `bufToGuid` method was silently failing and returning only the dashes in the guid string without any alphanumeric characters. ([code ref](https://github.com/bitwarden/directory-connector/blob/main/src/services/ldap-directory.service.ts#L243-L245 …

[PM-13007] Fix Active Directory externalId parsing

---

package-lock.json
package.json
tsconfig.eslint.json

https://bitwarden.atlassian.net/browse/PM-16412
Instead of upgrading `typescript-transform-paths` in #697 , I found that it's no longer required as it's already been replaced by `tsconfig-paths-webpack-plugin` (which is also what `clients` is using). We can remove it with no ill effects.
- ❓ …

[PM-16412] Remove typescript-transform-paths dependency

---

src/app/tabs/dashboard.component.html
src/app/tabs/tabs.component.html

[CL-570](https://bitwarden.atlassian.net/browse/CL-570)
We are in the process of switching to a new set of icons. The first step is to deprecate existing icons that won't be getting replacements. In this PR, the design guidance was to remove the icons entirely rather than swap them with icons that will get replacements. This also means removing a few other icons for consistency's sake, and after reviewing with design, changing the button color for the "stop" button to better differentiate it for users who can perceive color.
| Before | After |
|--------|--------|
| <img width="906" alt="Screenshot 2025-03-03 at 11 16 24 AM" src="https://github.com/user-attachments/assets/52ab7353-34bc-4186-bd15-027ee263ca75" /> | <img width="906" alt="Screenshot 2025-03-03 at 11 25 56 AM" …

[CL-570] Remove deprecated icons from use

---

.github/workflows/enforce-labels.yml

[BRE-848](https://bitwarden.atlassian.net/browse/BRE-848)
Adding permissions to all workflows not being updated by [BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
This will prepare for changing the org wide GitHub actions setting to `contents:read` and `packages:read` as the default permissions provided to workflows.
- Protected functional changes with optionality (feature flags)
- 👍 (`:+1:`) or similar …

[BRE-848] Add Workflow Permissions

---

README.md
src/abstractions/state.service.ts
src/app/tabs/settings.component.html
src/app/tabs/settings.component.ts
src/commands/config.command.ts
src/enums/directoryType.ts
src/models/account.ts
src/models/entraIdConfiguration.ts
src/program.ts
src/services/directory-factory.service.ts
src/services/entra-id-directory.service.ts
src/services/state.service.ts
src/services/stateMigration.service.ts

[PM-21187](https://bitwarden.atlassian.net/browse/PM-21187)
This renames Azure AD to Entra ID. It includes file names and commands. Existing configs should continue to work, but will be assigned to entra config behind the scenes.
- 🤔 (`:thinking:`) or 💭 …

[PM-21187] Rename Azure AD to Entra ID

---

.github/workflows/build.yml
.github/workflows/integration-test.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/version-bump.yml

https://bitwarden.atlassian.net/browse/VULN-285
Perform cleanup of existing workflows to be in compliance with Zizmor and bwwl.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …

Clean up workflow files from Zizmor output
